# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pMuUYqvWh8kshTbkzk393UoOrfaPzHL1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

# Load the dataset
df = pd.read_csv(r'/content/Cognifyz Dataset.csv')
df

df.isnull().sum()

"""#Step 1: Datecting NA, N/A and na Values

"""

missing_value =["N/a","na","Null",np.nan]
df = pd.read_csv(r'/content/Cognifyz Dataset.csv', na_values = missing_value)

df.isnull().sum()

df.isnull().any()

sns.heatmap(df.isnull(), yticklabels = False)

"""#Step 2: Remove the Missing Values"""

df.dropna(how ='all')

# Data cleaning
# 1. Handle missing values
df.dropna(subset=['Cuisines'], inplace=True)  # Drop rows with missing 'Cuisines'
df['Cuisines'] = df['Cuisines'].fillna(0)  # Fill missing 'Number of Dead' values with 0
df

df.fillna(method='bfill')

df.interpolate()